// estructurasBase.js

const estructurasBase = {
  estrategia1: {
    ejecutivo: [
    { texto: "Tú (Ejecutivo – 2000 VO)", clase: "ejecutivo" }
  ],
    elite: [
      { texto: "Tú (Elite)", clase: "elite" },
    ],
    premier: [
    { texto: "Tú (Premier)", clase: "premier" },
    { texto: "├ Ejecutivo 1 (pierna A)", clase: "nivel-1" },
    { texto: "└ Ejecutivo 2 (pierna B)", clase: "nivel-1" }
  ],
    silver: [
      { texto: "Tú (Plata)", clase: "silver" },
    { texto: "├ Elite 1 (pierna A)", clase: "nivel-1" },
    { texto: "├ Elite 2 (pierna B)", clase: "nivel-1" },
    { texto: "└ Elite 3 (pierna C)", clase: "nivel-1" }
    ],
    gold: [
    { texto: "Tú (Oro)", clase: "gold" },
    { texto: "├ Premier 1 (pierna A)", clase: "nivel-1" },
    { texto: "│  ├ Ejecutivo A1", clase: "nivel-2" },
    { texto: "│  ├ Ejecutivo A2", clase: "nivel-2" },
    { texto: "├ Premier 2 (pierna B)", clase: "nivel-1" },
    { texto: "│  ├ Ejecutivo B1", clase: "nivel-2" },
    { texto: "│  ├ Ejecutivo B2", clase: "nivel-2" },
    { texto: "└ Premier 3 (pierna C)", clase: "nivel-1" },
    { texto: "│  ├ Ejecutivo C1", clase: "nivel-2" },
    { texto: "│  ├ Ejecutivo C2", clase: "nivel-2" },
  ],
    platinum: [
{ texto: "Tú (Platino)", clase: "platinum" },
    { texto: "├ Plata 1 (pierna A)", clase: "nivel-1" },
    { texto: "│  ├ Elite A1", clase: "nivel-2" },
    { texto: "│  ├ Elite A2", clase: "nivel-2" },   
    { texto: "│  ├ Elite A3", clase: "nivel-2" },
    { texto: "├ Plata 2 (pierna B)", clase: "nivel-1" },
    { texto: "│  ├ Elite B1", clase: "nivel-2" },
    { texto: "│  ├ Elite B2", clase: "nivel-2" },
    { texto: "│  └ Elite B3", clase: "nivel-2" },
    { texto: "└ Plata 3 (pierna C)", clase: "nivel-1" },
    { texto: "│  ├ Elite C1", clase: "nivel-2" },
    { texto: "│  ├ Elite C2", clase: "nivel-2" },
    { texto: "│  └ Elite C3", clase: "nivel-2" },
    ],
    diamond: [
    { texto: "Tú (Diamante)", clase: "diamond" },
    { texto: "├ Plata 1 (pierna A)", clase: "nivel-1" },
    { texto: "│   ├ Elite A1", clase: "nivel-2" },
    { texto: "│   ├ Elite A2", clase: "nivel-2" },
    { texto: "│   ├ Elite A3", clase: "nivel-2" },
    { texto: "├ Plata 2 (pierna B)", clase: "nivel-1" },
    { texto: "│   ├ Elite B1", clase: "nivel-2" },
    { texto: "│   ├ Elite B2", clase: "nivel-2" },
    { texto: "│   └ Elite B3", clase: "nivel-2" },
    { texto: "├ Plata 3 (pierna C)", clase: "nivel-1" },
    { texto: "│   ├ Elite C1", clase: "nivel-2" },
    { texto: "│   ├ Elite C2", clase: "nivel-2" },
    { texto: "│   └ Elite C3", clase: "nivel-2" },
    { texto: "└ Plata 4 (pierna D)", clase: "nivel-1" },
    { texto: "│   ├ Elite D1", clase: "nivel-2" },
    { texto: "│   ├ Elite D2", clase: "nivel-2" },
    { texto: "│   └ Elite D3", clase: "nivel-2" },
    ],
    blue: [
    { texto: "Tú (Diamante Azul)", clase: "blue" },
    { texto: "├ Oro 1 (pierna A)", clase: "nivel-1" },
    { texto: "│   ├ Premier A1", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo A1a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo A1a2", clase: "nivel-3" },
    { texto: "│   ├ Premier A2", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo A2a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo A2a2", clase: "nivel-3" },
    { texto: "│   └ Premier A3", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo A3a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo A3a2", clase: "nivel-3" },
    { texto: "├ Oro 2 (pierna B)", clase: "nivel-1" },
    { texto: "│   ├ Premier B1", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo B1a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo B1a2", clase: "nivel-3" },
    { texto: "│   ├ Premier B2", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo B2a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo B2a2", clase: "nivel-3" },
    { texto: "│   ├ Premier B3", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo B3a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo B3a2", clase: "nivel-3" },
    { texto: "├ Oro 3 (pierna C)", clase: "nivel-1" },
    { texto: "│   ├ Premier C1", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo C1a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo C1a2", clase: "nivel-3" },
    { texto: "│   ├ Premier C2", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo C2a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo C2a2", clase: "nivel-3" },
    { texto: "│   ├ Premier C3", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo C3a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo C3a2", clase: "nivel-3" },
    { texto: "├ Oro 4 (pierna D)", clase: "nivel-1" },
    { texto: "│   ├ Premier D1", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo D1a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo D1a2", clase: "nivel-3" },
    { texto: "│   ├ Premier D2", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo D2a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo D2a2", clase: "nivel-3" },
    { texto: "│   ├ Premier D3", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo D3a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo D3a2", clase: "nivel-3" },
    { texto: "└ Oro 5 (pierna E)", clase: "nivel-1" },
    { texto: "│   ├ Premier E1", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo E1a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo E1a2", clase: "nivel-3" },
    { texto: "│   ├ Premier E2", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo E2a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo E2a2", clase: "nivel-3" },
    { texto: "│   ├ Premier E3", clase: "nivel-2" },
    { texto: "│   │   ├ Ejecutivo E3a1", clase: "nivel-3" },
    { texto: "│   │   └ Ejecutivo E3a2", clase: "nivel-3" },
    ],
    presidential: [
{ texto: "Tú (Presidencial)", clase: "presidential" },
    { texto: "├ Platino 1 (pierna A)", clase: "nivel-1" },
    { texto: "│ ├ Silver A1a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite A1a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite A1a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite A1a3", clase: "nivel-3" },
    { texto: "│ ├ Silver A2a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite A2a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite A2a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite A2a3", clase: "nivel-3" },
    { texto: "│ ├ Silver A3a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite A3a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite A3a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite A3a3", clase: "nivel-3" },
    { texto: "├ Platino 2 (pierna B)", clase: "nivel-1" },
    { texto: "│ ├ Silver B1a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite B1a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite B1a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite B1a3", clase: "nivel-3" },
    { texto: "│ ├ Silver B2a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite B2a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite B2a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite B2a3", clase: "nivel-3" },
    { texto: "│ ├ Silver B3a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite B3a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite B3a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite B3a3", clase: "nivel-3" },
    { texto: "├ Platino 3 (pierna C)", clase: "nivel-1" },
    { texto: "│ ├ Silver C1a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite C1a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite C1a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite C1a3", clase: "nivel-3" },
    { texto: "│ ├ Silver C2a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite C2a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite C2a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite C2a3", clase: "nivel-3" },
    { texto: "│ ├ Silver C3a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite C3a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite C3a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite C3a3", clase: "nivel-3" },
    { texto: "├ Platino 4 (pierna D)", clase: "nivel-1" },
    { texto: "│ ├ Silver D1a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite D1a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite D1a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite D1a3", clase: "nivel-3" },
    { texto: "│ ├ Silver D2a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite D2a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite D2a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite D2a3", clase: "nivel-3" },
    { texto: "│ ├ Silver D3a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite D3a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite D3a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite D3a3", clase: "nivel-3" },
    { texto: "├ Platino 5 (pierna E)", clase: "nivel-1" },
    { texto: "│ ├ Silver E1a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite E1a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite E1a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite E1a3", clase: "nivel-3" },
    { texto: "│ ├ Silver E2a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite E2a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite E2a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite E2a3", clase: "nivel-3" },
    { texto: "│ ├ Silver E3a", clase: "nivel-2" },    
    { texto: "│ │ ├ Elite E3a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite E3a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite E3a3", clase: "nivel-3" },
    { texto: "└ Platino 6 (pierna F)", clase: "nivel-1" },
    { texto: "│ │ ├ Elite F1a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite F1a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite F1a3", clase: "nivel-3" },
    { texto: "│ ├ Silver F2a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite F2a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite F2a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite F2a3", clase: "nivel-3" },
    { texto: "│ ├ Silver F3a", clase: "nivel-2" },
    { texto: "│ │ ├ Elite F3a1", clase: "nivel-3" },
    { texto: "│ │ ├ Elite F3a2", clase: "nivel-3" },
    { texto: "│ │ ├ Elite F3a3", clase: "nivel-3" },
    ],
  },
  estrategia2: {
  elite: [
    { texto: "Tú (Elite)", clase: "elite" },
    { texto: "├ Miembro A (con 1000 OV)", clase: "nivel-1" },
    { texto: "└ Miembro B (con 1000 OV)", clase: "nivel-1" },
  ],
  silver: [
    { texto: "Tú (Silver)", clase: "silver" },
    { texto: "├ Elite 1 (pierna A)", clase: "nivel-1" },
    { texto: "│  └ Apoyos A1", clase: "nivel-2" },
    { texto: "│  └ Apoyos A2", clase: "nivel-2" },
    { texto: "├ Elite 2 (pierna B)", clase: "nivel-1" },
    { texto: "│  └ Apoyos B1", clase: "nivel-2" },
    { texto: "│  └ Apoyos B2", clase: "nivel-2" },
    { texto: "└ Elite 3 (pierna C)", clase: "nivel-1" },
    { texto: "   └ Apoyos C1", clase: "nivel-2" },
    { texto: "   └ Apoyos C2", clase: "nivel-2" },
  ],
  gold: [
    { texto: "Tú (Gold)", clase: "gold" },
    { texto: "├ Premier 1 (pierna A)", clase: "nivel-1" },
    { texto: "│  ├ Ejecutivo A1", clase: "nivel-2" },
    { texto: "│  ├ Ejecutivo A2", clase: "nivel-2" },
    { texto: "│  └ Ejecutivo A3", clase: "nivel-2" },
    { texto: "├ Premier 2 (pierna B)", clase: "nivel-1" },
    { texto: "│  ├ Ejecutivo B1", clase: "nivel-2" },
    { texto: "│  └ Ejecutivo B2", clase: "nivel-2" },
    { texto: "└ Premier 3 (pierna C)", clase: "nivel-1" },
    { texto: "   ├ Ejecutivo C1", clase: "nivel-2" },
    { texto: "   └ Ejecutivo C2", clase: "nivel-2" }
  ],
  platinum: [
    { texto: "Tú (Platinum)", clase: "platinum" },
    { texto: "├ Silver 1 (pierna A)", clase: "nivel-1" },
    { texto: "│  ├ Elite A1", clase: "nivel-2" },
    { texto: "│  └ Elite A2", clase: "nivel-2" },
    { texto: "├ Silver 2 (pierna B)", clase: "nivel-1" },
    { texto: "│  ├ Elite B1", clase: "nivel-2" },
    { texto: "│  └ Elite B2", clase: "nivel-2" },
    { texto: "└ Silver 3 (pierna C)", clase: "nivel-1" },
    { texto: "   ├ Elite C1", clase: "nivel-2" },
    { texto: "   └ Elite C2", clase: "nivel-2" }
  ],
  diamond: [
    { texto: "Tú (Diamond)", clase: "diamond" },
    { texto: "├ Silver 1", clase: "nivel-1" },
    { texto: "├ Silver 2", clase: "nivel-1" },
    { texto: "├ Silver 3", clase: "nivel-1" },
    { texto: "└ Silver 4", clase: "nivel-1" }
  ],
  blue: [
    { texto: "Tú (Blue Diamond)", clase: "blue" },
    { texto: "├ Gold 1", clase: "nivel-1" },
    { texto: "├ Gold 2", clase: "nivel-1" },
    { texto: "├ Gold 3", clase: "nivel-1" },
    { texto: "├ Gold 4", clase: "nivel-1" },
    { texto: "└ Gold 5", clase: "nivel-1" }
  ],
  presidential: [
    { texto: "Tú (Presidential Diamond)", clase: "presidential" },
    { texto: "├ Platinum 1", clase: "nivel-1" },
    { texto: "├ Platinum 2", clase: "nivel-1" },
    { texto: "├ Platinum 3", clase: "nivel-1" },
    { texto: "├ Platinum 4", clase: "nivel-1" },
    { texto: "├ Platinum 5", clase: "nivel-1" },
    { texto: "└ Platinum 6", clase: "nivel-1" }
  ]
},

  estrategia3: {
  elite: [
    { texto: "Tú (Elite)", clase: "elite" }
  ],
  silver: [
    { texto: "Tú (Silver)", clase: "silver" },
    { texto: "└ Línea Única: Elite", clase: "elite" }
  ],
  gold: [
    { texto: "Tú (Gold)", clase: "gold" },
    { texto: "├ Línea 1: Silver", clase: "silver" },
    { texto: "│  └ Línea Única: Elite", clase: "elite" },
    { texto: "└ Línea 2: Silver", clase: "silver" },
    { texto: "   └ Línea Única: Elite", clase: "elite" }
  ],
  platinum: [
    { texto: "Tú (Platinum)", clase: "platinum" },
    { texto: "├ Línea 1: Gold", clase: "gold" },
    { texto: "│  ├ Línea 1: Silver", clase: "silver" },
    { texto: "│  │  └ Línea Única: Elite", clase: "elite" },
    { texto: "│  └ Línea 2: Silver", clase: "silver" },
    { texto: "│     └ Línea Única: Elite", clase: "elite" },
    { texto: "└ Línea 2: Gold", clase: "gold" },
    { texto: "   ├ Línea 1: Silver", clase: "silver" },
    { texto: "   │  └ Línea Única: Elite", clase: "elite" },
    { texto: "   └ Línea 2: Silver", clase: "silver" },
    { texto: "      └ Línea Única: Elite", clase: "elite" }
  ],
  diamond: [
    { texto: "Tú (Diamond)", clase: "diamond" },
    { texto: "├ Línea 1: Platinum", clase: "platinum" },
    { texto: "│  ├ Línea 1: Gold", clase: "gold" },
    { texto: "│  │  ├ Línea 1: Silver", clase: "silver" },
    { texto: "│  │  │  └ Línea Única: Elite", clase: "elite" },
    { texto: "│  │  └ Línea 2: Silver", clase: "silver" },
    { texto: "│  │     └ Línea Única: Elite", clase: "elite" },
    { texto: "│  └ Línea 2: Gold", clase: "gold" },
    { texto: "│     ├ Línea 1: Silver", clase: "silver" },
    { texto: "│     │  └ Línea Única: Elite", clase: "elite" },
    { texto: "│     └ Línea 2: Silver", clase: "silver" },
    { texto: "│        └ Línea Única: Elite", clase: "elite" },
    { texto: "└ Línea 2: Platinum", clase: "platinum" },
    { texto: "   ├ Línea 1: Gold", clase: "gold" },
    { texto: "   │  ├ Línea 1: Silver", clase: "silver" },
    { texto: "   │  │  └ Línea Única: Elite", clase: "elite" },
    { texto: "   │  └ Línea 2: Silver", clase: "silver" },
    { texto: "   │     └ Línea Única: Elite", clase: "elite" },
    { texto: "   └ Línea 2: Gold", clase: "gold" },
    { texto: "      ├ Línea 1: Silver", clase: "silver" },
    { texto: "      │  └ Línea Única: Elite", clase: "elite" },
    { texto: "      └ Línea 2: Silver", clase: "silver" },
    { texto: "         └ Línea Única: Elite", clase: "elite" }
  ],
  blue: [
    { texto: "Tú (Blue Diamond)", clase: "blue" },
    { texto: "├ Línea 1: Diamond", clase: "diamond" },
    { texto: "│  └ (…continúa duplicando la estructura de Platinum…)", clase: "texto" },
    { texto: "└ Línea 2: Diamond", clase: "diamond" },
    { texto: "   └ (…continúa duplicando la estructura de Platinum…)", clase: "texto" }
  ],
  presidential: [
    { texto: "Tú (Presidential Diamond)", clase: "presidential" },
    { texto: "├ Línea 1: Blue Diamond", clase: "blue" },
    { texto: "│  └ (…continúa duplicando la estructura de Diamond…)", clase: "texto" },
    { texto: "└ Línea 2: Blue Diamond", clase: "blue" },
    { texto: "   └ (…continúa duplicando la estructura de Diamond…)", clase: "texto" }
  ],
},

estrategia4: {
  elite: [
    { texto: "Tú (Elite)", clase: "elite" }
  ],
  silver: [
    { texto: "Tú (Silver)", clase: "silver" },
    { texto: "└ Línea 1: Elite", clase: "elite" },
    { texto: "   └ Miembro A", clase: "miembro" }
  ],
  gold: [
    { texto: "Tú (Gold)", clase: "gold" },
    { texto: "├ Línea 1: Silver", clase: "silver" },
    { texto: "│  └ Línea: Elite", clase: "elite" },
    { texto: "│     └ Miembro B", clase: "miembro" },
    { texto: "└ Línea 2: Elite", clase: "elite" },
    { texto: "   └ Miembro C", clase: "miembro" }
  ],
  platinum: [
    { texto: "Tú (Platinum)", clase: "platinum" },
    { texto: "├ Línea 1: Gold", clase: "gold" },
    { texto: "│  ├ Línea: Silver", clase: "silver" },
    { texto: "│  │  └ Línea: Elite", clase: "elite" },
    { texto: "│  │     └ Miembro D", clase: "miembro" },
    { texto: "│  └ Línea: Elite", clase: "elite" },
    { texto: "└ Línea 2: Silver", clase: "silver" },
    { texto: "   └ Línea: Elite", clase: "elite" },
    { texto: "      └ Miembro E", clase: "miembro" }
  ],
  diamond: [
    { texto: "Tú (Diamond)", clase: "diamond" },
    { texto: "├ Línea 1: Platinum", clase: "platinum" },
    { texto: "│  ├ Línea: Gold", clase: "gold" },
    { texto: "│  │  ├ Línea: Silver", clase: "silver" },
    { texto: "│  │  │  └ Línea: Elite", clase: "elite" },
    { texto: "│  │  │     └ Miembro F", clase: "miembro" },
    { texto: "│  │  └ Línea: Elite", clase: "elite" },
    { texto: "│  └ Línea: Silver", clase: "silver" },
    { texto: "└ Línea 2: Gold", clase: "gold" },
    { texto: "   ├ Línea: Silver", clase: "silver" },
    { texto: "   │  └ Línea: Elite", clase: "elite" },
    { texto: "   │     └ Miembro G", clase: "miembro" },
    { texto: "   └ Línea: Elite", clase: "elite" }
  ],
  blue: [
    { texto: "Tú (Blue Diamond)", clase: "blue" },
    { texto: "├ Línea 1: Diamond", clase: "diamond" },
    { texto: "│  ├ Línea: Platinum", clase: "platinum" },
    { texto: "│  │  ├ Línea: Gold", clase: "gold" },
    { texto: "│  │  │  ├ Línea: Silver", clase: "silver" },
    { texto: "│  │  │  │  └ Línea: Elite", clase: "elite" },
    { texto: "│  │  │  │     └ Miembro H", clase: "miembro" },
    { texto: "│  │  └ Línea: Silver", clase: "silver" },
    { texto: "│  └ Línea: Gold", clase: "gold" },
    { texto: "└ Línea 2: Platinum", clase: "platinum" },
    { texto: "   ├ Línea: Gold", clase: "gold" },
    { texto: "   │  └ Línea: Silver", clase: "silver" },
    { texto: "   │     └ Línea: Elite", clase: "elite" },
    { texto: "   └ Línea: Silver", clase: "silver" }
  ],
  presidential: [
    { texto: "Tú (Presidential Diamond)", clase: "presidential" },
    { texto: "├ Línea 1: Blue Diamond", clase: "blue" },
    { texto: "│  ├ Línea: Diamond", clase: "diamond" },
    { texto: "│  │  ├ Línea: Platinum", clase: "platinum" },
    { texto: "│  │  │  └ Línea: Gold", clase: "gold" },
    { texto: "│  │  │     └ Línea: Silver", clase: "silver" },
    { texto: "│  │  │        └ Línea: Elite", clase: "elite" },
    { texto: "│  │  │           └ Miembro I", clase: "miembro" },
    { texto: "│  │  └ Línea: Gold", clase: "gold" },
    { texto: "│  └ Línea: Platinum", clase: "platinum" },
    { texto: "└ Línea 2: Diamond", clase: "diamond" },
    { texto: "   └ Línea: Platinum", clase: "platinum" }
    ],
  },

  estrategia5: {
  elite: [
    { texto: "Tú (Elite)", clase: "elite" }
  ],
  silver: [
    { texto: "Tú (Silver)", clase: "silver" },
    { texto: "├ Núcleo 1: Elite", clase: "elite" },
    { texto: "└ Núcleo 2: Elite", clase: "elite" }
  ],
  gold: [
    { texto: "Tú (Gold)", clase: "gold" },
    { texto: "├ Núcleo 1: Silver", clase: "silver" },
    { texto: "│  ├ Línea: Elite", clase: "elite" },
    { texto: "│  └ Línea: Elite", clase: "elite" },
    { texto: "└ Núcleo 2: Silver", clase: "silver" },
    { texto: "   ├ Línea: Elite", clase: "elite" },
    { texto: "   └ Línea: Elite", clase: "elite" }
  ],
  platinum: [
    { texto: "Tú (Platinum)", clase: "platinum" },
    { texto: "├ Núcleo 1: Gold", clase: "gold" },
    { texto: "│  ├ Línea: Silver", clase: "silver" },
    { texto: "│  │  └ Línea: Elite", clase: "elite" },
    { texto: "│  └ Línea: Silver", clase: "silver" },
    { texto: "└ Núcleo 2: Silver", clase: "silver" },
    { texto: "   └ Línea: Elite", clase: "elite" }
  ],
  diamond: [
    { texto: "Tú (Diamond)", clase: "diamond" },
    { texto: "├ Núcleo 1: Platinum", clase: "platinum" },
    { texto: "│  ├ Línea: Gold", clase: "gold" },
    { texto: "│  │  ├ Línea: Silver", clase: "silver" },
    { texto: "│  │  │  └ Línea: Elite", clase: "elite" },
    { texto: "│  │  └ Línea: Silver", clase: "silver" },
    { texto: "│  └ Línea: Silver", clase: "silver" },
    { texto: "└ Núcleo 2: Gold", clase: "gold" },
    { texto: "   └ Línea: Silver", clase: "silver" }
  ],
  blue: [
    { texto: "Tú (Blue Diamond)", clase: "blue" },
    { texto: "├ Núcleo 1: Diamond", clase: "diamond" },
    { texto: "│  ├ Línea: Platinum", clase: "platinum" },
    { texto: "│  │  └ Línea: Gold", clase: "gold" },
    { texto: "│  │     └ Línea: Silver", clase: "silver" },
    { texto: "│  └ Línea: Gold", clase: "gold" },
    { texto: "└ Núcleo 2: Platinum", clase: "platinum" },
    { texto: "   └ Línea: Silver", clase: "silver" }
  ],
  presidential: [
    { texto: "Tú (Presidential Diamond)", clase: "presidential" },
    { texto: "├ Núcleo 1: Blue Diamond", clase: "blue" },
    { texto: "│  ├ Línea: Diamond", clase: "diamond" },
    { texto: "│  │  ├ Línea: Platinum", clase: "platinum" },
    { texto: "│  │  │  └ Línea: Gold", clase: "gold" },
    { texto: "│  │  │     └ Línea: Silver", clase: "silver" },
    { texto: "│  │  └ Línea: Gold", clase: "gold" },
    { texto: "│  └ Línea: Platinum", clase: "platinum" },
    { texto: "└ Núcleo 2: Diamond", clase: "diamond" },
    { texto: "   └ Línea: Gold", clase: "gold" }
    ],
  },

  estrategia6: {
  elite: [
    { texto: "Tú (Elite)", clase: "elite" }
  ],
  silver: [
    { texto: "Tú (Silver)", clase: "silver" },
    { texto: "├ Línea 1: Elite", clase: "elite" },
    { texto: "└ Línea 2: Elite", clase: "elite" }
  ],
  gold: [
    { texto: "Tú (Gold)", clase: "gold" },
    { texto: "├ Línea 1: Silver", clase: "silver" },
    { texto: "│  ├ Línea 1: Elite", clase: "elite" },
    { texto: "│  └ Línea 2: Elite", clase: "elite" },
    { texto: "└ Línea 2: Silver", clase: "silver" },
    { texto: "   ├ Línea 1: Elite", clase: "elite" },
    { texto: "   └ Línea 2: Elite", clase: "elite" }
  ],
  platinum: [
    { texto: "Tú (Platinum)", clase: "platinum" },
    { texto: "├ Línea 1: Gold", clase: "gold" },
    { texto: "│  ├ Línea 1: Silver", clase: "silver" },
    { texto: "│  │  ├ Línea 1: Elite", clase: "elite" },
    { texto: "│  │  └ Línea 2: Elite", clase: "elite" },
    { texto: "│  └ Línea 2: Silver", clase: "silver" },
    { texto: "│     └ Línea 1: Elite", clase: "elite" },
    { texto: "└ Línea 2: Gold", clase: "gold" },
    { texto: "   ├ Línea 1: Silver", clase: "silver" },
    { texto: "   │  └ Línea 1: Elite", clase: "elite" },
    { texto: "   └ Línea 2: Silver", clase: "silver" },
    { texto: "      └ Línea 1: Elite", clase: "elite" }
  ],
  diamond: [
    { texto: "Tú (Diamond)", clase: "diamond" },
    { texto: "├ Línea 1: Platinum", clase: "platinum" },
    { texto: "│  ├ Línea 1: Gold", clase: "gold" },
    { texto: "│  │  ├ Línea 1: Silver", clase: "silver" },
    { texto: "│  │  │  └ Línea 1: Elite", clase: "elite" },
    { texto: "│  │  └ Línea 2: Silver", clase: "silver" },
    { texto: "│  └ Línea 2: Gold", clase: "gold" },
    { texto: "│     └ Línea 1: Silver", clase: "silver" },
    { texto: "└ Línea 2: Gold", clase: "gold" },
    { texto: "   ├ Línea 1: Silver", clase: "silver" },
    { texto: "   │  └ Línea 1: Elite", clase: "elite" },
    { texto: "   └ Línea 2: Silver", clase: "silver" },
    { texto: "      └ Línea 1: Elite", clase: "elite" }
  ],
  blue: [
    { texto: "Tú (Blue Diamond)", clase: "blue" },
    { texto: "├ Línea 1: Diamond", clase: "diamond" },
    { texto: "│  ├ Línea 1: Platinum", clase: "platinum" },
    { texto: "│  │  ├ Línea 1: Gold", clase: "gold" },
    { texto: "│  │  │  └ Línea 1: Silver", clase: "silver" },
    { texto: "│  │  │     └ Línea: Elite", clase: "elite" },
    { texto: "│  └ Línea 2: Gold", clase: "gold" },
    { texto: "│     └ Línea 1: Silver", clase: "silver" },
    { texto: "└ Línea 2: Platinum", clase: "platinum" },
    { texto: "   ├ Línea 1: Gold", clase: "gold" },
    { texto: "   │  └ Línea 1: Silver", clase: "silver" },
    { texto: "   │     └ Línea: Elite", clase: "elite" },
    { texto: "   └ Línea 2: Silver", clase: "silver" },
    { texto: "      └ Línea: Elite", clase: "elite" }
  ],
  presidential: [
    { texto: "Tú (Presidential Diamond)", clase: "presidential" },
    { texto: "├ Línea 1: Blue Diamond", clase: "blue" },
    { texto: "│  ├ Línea 1: Diamond", clase: "diamond" },
    { texto: "│  │  ├ Línea 1: Platinum", clase: "platinum" },
    { texto: "│  │  │  └ Línea 1: Gold", clase: "gold" },
    { texto: "│  │  │     └ Línea: Silver", clase: "silver" },
    { texto: "│  │  │        └ Línea: Elite", clase: "elite" },
    { texto: "│  │  └ Línea 2: Gold", clase: "gold" },
    { texto: "│  │     └ Línea: Silver", clase: "silver" },
    { texto: "│  └ Línea 2: Platinum", clase: "platinum" },
    { texto: "│     └ Línea: Silver", clase: "silver" },
    { texto: "└ Línea 2: Diamond", clase: "diamond" },
    { texto: "   └ Línea: Gold", clase: "gold" },
    { texto: "      └ Línea: Silver", clase: "silver" },
    { texto: "         └ Línea: Elite", clase: "elite" },
    ],
  },
}

